steps:

#step 1
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
   '-c',
   'docker pull gcr.io/$PROJECT_ID/{APP_NAME}:latest || exit 0'
  ]

#step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build',
   '-t',
   'gcr.io/$PROJECT_ID/{APP_NAME}:$BRANCH_NAME-$COMMIT_SHA',
   '-t',
   'gcr.io/$PROJECT_ID/{APP_NAME}:latest',
   '.'
  ]

#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE={CLUSTER_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER={CLUSTER_NAME}'

#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set',
   'image',
   'deployment',
   '{APP_NAME}',
   '{APP_NAME}=gcr.io/$PROJECT_ID/{APP_NAME}:$BRANCH_NAME-$COMMIT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE={CLUSTER_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER={CLUSTER_NAME}'

# push images to Google Container Registry with tags
images: [
   'gcr.io/$PROJECT_ID/{APP_NAME}:$BRANCH_NAME-$COMMIT_SHA',
   'gcr.io/$PROJECT_ID/{APP_NAME}:latest'
  ]
